/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;
import desain.RoundedPanel;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author zaida
 */
public class mengubahdatagame extends javax.swing.JFrame {

    /**
     * Creates new form mengubahdatagame
     */
    public mengubahdatagame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mengubahdatagame = new javax.swing.JLabel();
        border = new RoundedPanel(20);
        jTextField1 = new javax.swing.JTextField();
        border2 = new RoundedPanel(20);
        nama2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        border3 = new RoundedPanel(20);
        nama3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        border4 = new RoundedPanel(20);
        nama4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        border5 = new RoundedPanel(20);
        nama5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        border6 = new RoundedPanel(20);
        nama6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        border7 = new RoundedPanel(20);
        nama7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mengubahdatagame.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        mengubahdatagame.setForeground(new java.awt.Color(255, 255, 255));
        mengubahdatagame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mengubahdatagame.setText("Mengubah Data Game");
        getContentPane().add(mengubahdatagame, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        border.setBackground(new java.awt.Color(38, 76, 89));

        jTextField1.setBackground(new java.awt.Color(38, 76, 89));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Mencari...");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                .addContainerGap())
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 925, 45));

        border2.setBackground(new java.awt.Color(38, 76, 89));

        nama2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama2.setForeground(new java.awt.Color(255, 255, 255));
        nama2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama2.setText("Nama : ");

        jTextField2.setBackground(new java.awt.Color(38, 76, 89));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout border2Layout = new javax.swing.GroupLayout(border2);
        border2.setLayout(border2Layout);
        border2Layout.setHorizontalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nama2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        border2Layout.setVerticalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(border2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 925, 45));

        border3.setBackground(new java.awt.Color(38, 76, 89));

        nama3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama3.setForeground(new java.awt.Color(255, 255, 255));
        nama3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama3.setText("Kategori :");

        jTextField4.setBackground(new java.awt.Color(38, 76, 89));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout border3Layout = new javax.swing.GroupLayout(border3);
        border3.setLayout(border3Layout);
        border3Layout.setHorizontalGroup(
            border3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nama3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        border3Layout.setVerticalGroup(
            border3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(border3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(border3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 925, 45));

        border4.setBackground(new java.awt.Color(38, 76, 89));

        nama4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama4.setForeground(new java.awt.Color(255, 255, 255));
        nama4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama4.setText("Perangkat :");

        jTextField3.setBackground(new java.awt.Color(38, 76, 89));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout border4Layout = new javax.swing.GroupLayout(border4);
        border4.setLayout(border4Layout);
        border4Layout.setHorizontalGroup(
            border4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nama4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        border4Layout.setVerticalGroup(
            border4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(border4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(border4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 925, 45));

        border5.setBackground(new java.awt.Color(38, 76, 89));

        nama5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama5.setForeground(new java.awt.Color(255, 255, 255));
        nama5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama5.setText("Harga : ");

        jTextField5.setBackground(new java.awt.Color(38, 76, 89));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout border5Layout = new javax.swing.GroupLayout(border5);
        border5.setLayout(border5Layout);
        border5Layout.setHorizontalGroup(
            border5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nama5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );
        border5Layout.setVerticalGroup(
            border5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(border5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(border5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 925, 45));

        border6.setBackground(new java.awt.Color(38, 76, 89));

        nama6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama6.setForeground(new java.awt.Color(255, 255, 255));
        nama6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama6.setText("Umur Pengguna :");

        jTextField6.setBackground(new java.awt.Color(38, 76, 89));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout border6Layout = new javax.swing.GroupLayout(border6);
        border6.setLayout(border6Layout);
        border6Layout.setHorizontalGroup(
            border6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nama6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        border6Layout.setVerticalGroup(
            border6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(border6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(border6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 925, 45));

        border7.setBackground(new java.awt.Color(38, 76, 89));

        nama7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama7.setForeground(new java.awt.Color(255, 255, 255));
        nama7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama7.setText("Upload Foto :");

        jButton2.setBackground(new java.awt.Color(32, 223, 127));
        jButton2.setText("Unggah");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout border7Layout = new javax.swing.GroupLayout(border7);
        border7.setLayout(border7Layout);
        border7Layout.setHorizontalGroup(
            border7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(border7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nama7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 668, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        border7Layout.setVerticalGroup(
            border7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, border7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(border7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama7, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(border7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 925, 45));

        jButton1.setBackground(new java.awt.Color(38, 76, 89));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 90, 30));

        jButton3.setBackground(new java.awt.Color(32, 223, 127));
        jButton3.setText("Perbaharui");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 210, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/background.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Membuat JFileChooser untuk memilih file gambar
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
    fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

    // Filter untuk hanya memilih file gambar (jpg, png, gif)
    fileChooser.setAcceptAllFileFilterUsed(false);
    fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "png", "gif"));

    // Menampilkan dialog pemilihan file
    int result = fileChooser.showOpenDialog(null);
    if (result == JFileChooser.APPROVE_OPTION) {
        // Mendapatkan file yang dipilih
        File selectedFile = fileChooser.getSelectedFile();
        String path = selectedFile.getAbsolutePath();

        // Menampilkan gambar di JLabel
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT));
        jLabel1.setIcon(imageIcon);  // jLabel1 adalah label tempat menampilkan gambar
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          // Menampilkan dialog pop-up dengan pesan "Mengubah Data Game Selesai"
    JOptionPane.showMessageDialog(null, "Mengubah Data Game Selesai", "Informasi", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mengubahdatagame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mengubahdatagame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mengubahdatagame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mengubahdatagame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mengubahdatagame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel border;
    private javax.swing.JPanel border2;
    private javax.swing.JPanel border3;
    private javax.swing.JPanel border4;
    private javax.swing.JPanel border5;
    private javax.swing.JPanel border6;
    private javax.swing.JPanel border7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel mengubahdatagame;
    private javax.swing.JLabel nama2;
    private javax.swing.JLabel nama3;
    private javax.swing.JLabel nama4;
    private javax.swing.JLabel nama5;
    private javax.swing.JLabel nama6;
    private javax.swing.JLabel nama7;
    // End of variables declaration//GEN-END:variables
}
